// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlBKyWFCxTY5IdMezt10UozG9IPO0Av0Q',
    appId: '1:1058061786504:web:c885a5c382840be7feae3d',
    messagingSenderId: '1058061786504',
    projectId: 'ecommerce-app-94a04',
    authDomain: 'ecommerce-app-94a04.firebaseapp.com',
    storageBucket: 'ecommerce-app-94a04.appspot.com',
    measurementId: 'G-TE7BPNYLD3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlA-oFXbGQKs-OYQ5N4lVwbk6SFf3Rofg',
    appId: '1:1058061786504:android:8472f4f012a14daffeae3d',
    messagingSenderId: '1058061786504',
    projectId: 'ecommerce-app-94a04',
    storageBucket: 'ecommerce-app-94a04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtpngvxxHJ2AYbPvYKn1nUyz3qUWyGBxU',
    appId: '1:1058061786504:ios:f6b31118d56dd1dffeae3d',
    messagingSenderId: '1058061786504',
    projectId: 'ecommerce-app-94a04',
    storageBucket: 'ecommerce-app-94a04.appspot.com',
    iosBundleId: 'com.example.eCommerceUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtpngvxxHJ2AYbPvYKn1nUyz3qUWyGBxU',
    appId: '1:1058061786504:ios:f6b31118d56dd1dffeae3d',
    messagingSenderId: '1058061786504',
    projectId: 'ecommerce-app-94a04',
    storageBucket: 'ecommerce-app-94a04.appspot.com',
    iosBundleId: 'com.example.eCommerceUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlBKyWFCxTY5IdMezt10UozG9IPO0Av0Q',
    appId: '1:1058061786504:web:7eca3934b0199bcdfeae3d',
    messagingSenderId: '1058061786504',
    projectId: 'ecommerce-app-94a04',
    authDomain: 'ecommerce-app-94a04.firebaseapp.com',
    storageBucket: 'ecommerce-app-94a04.appspot.com',
    measurementId: 'G-JR8R6HNNKC',
  );
}
